### ISSUE TITLE
CSS being broken when opening Railz Connect

### ISSUE THREAD

**Issue by davidsonsns** [railz-ai/railz-connect#34]
For some reason when we open Railz Connect with `widget.open` or `widget.mount`, the app's CSS is breaking.

Environment:
- Nextjs 13
- [ChakraUI](https://chakra-ui.com/)
- railz-connect: 2.8.0

https://www.loom.com/share/1f93fe5cd7f54e0b9baee1fbd0249834?sid=08c6c45c-5214-4114-844f-320d8b83d76f

**Comment by gchittolina** [comment]
Hi David. We will look into it and let you know. Thanks.

**Comment by gchittolina** [comment]
Hi @davidsonsns , I wasn't able to reproduce the same issue, do you mind sharing a small example so we can better debug your issue?

**Comment by davidsonsns** [comment]
> Hi @davidsonsns , I wasn't able to reproduce the same issue, do you mind sharing a minimum code example so we can better debug your issue?

sure thing! I will create a repo with this. I will keep u posted

**Comment by spersico** [comment]
hey @davidsonsns thanks for taking the time to report and build the minimal example.

We are currently investigating what's happening. As far as we can see so far (though we might be wrong), there's a conflict between the styling engine of ChackraUI and the one used by Railz Connect.

We will keep you posted with our findings!

**Comment by gchittolina** [comment]
@davidsonsns It turns out there are CSS conflicts between our setup and Chakra's setup. We already have a solution in place and now we're just testing it to make sure it's all good. We will post here when we deploy the new Railz Connect version with a fix.

Thanks!

**Comment by davidsonsns** [comment]
Epic! Appreciate it guys

**Comment by gchittolina** [comment]
Hi @davidsonsns ! Just letting you know that the v2.8.1 patch has been released and it's available [here](https://www.npmjs.com/package/@railzai/railz-connect/v/2.8.1). 

Please let us know if it works on your side.

**Comment by davidsonsns** [comment]
hey @gchittolina, I just tested the proposed version and it seems to be working perfectly now without impacting other styles.

mind-blowing, I appreciate the effort from you and everyone involved 🥷
